%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                       % 
%    THE SPLIT GIBBS SAMPLER REVISITED: IMPROVEMENTS TO ITS ALGORITHMIC %
%    STRUCTURE AND AUGMENTED TARGET DISTRIBUTION                        %
%                                                                       %
%    To reproduce some of the numerical experiments illustrated in the  %
%    corresponding paper.                                               %
%                                                                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% to clear workspace
clear all;
close all;

%%% number of core processors
maxNumCompThreads(1);

% import folders
addpath sampling_algorithms;
addpath numerical_experiments;
addpath functions;
addpath images;
addpath data;

%%% initialize the random number generator to make the results repeatable
rng('default');
% %%% initialize the generator using a seed
rng(10);

% loading functions/variables/operators from numerical experiment
[X,Y,sigma,A,At,AtA,invQ] = cameraman_deconvolution();

% estimating hyperparameters using
% SAPG algorithm (see Algorithm 3.1 from paper)
[alpha, rho2] = SAPG_deb_TV('true_img',X,...
                            'obs_vector',Y,...
                            'transpose_operator',At,...
                            'inverse_precision_matrix',invQ,...
                            'number_samples_burn_in',2e3,...
                            'max_number_samples',1e5,...
                            'sigma',sigma,...
                            'tol_tv_param',1e-5,...
                            'tol_rho2_param',1e-5)

% MCMC sampler parameters
nSamples_burnIn = 1e2; % burn-in number of samples (to discard)
nSamples = 5e2; % number of samples to consider after burn-in
lipschitz_f = 1 / sigma^2; % Lipschitz constant of the likelihood
nStagesROCK = 15; % number of stages 's' of the (ls-)SK-ROCK method
percDt = 0.95; % fraction of the max (ls-)SK-ROCK step-size
MYParam = sigma^2; % Moreau-Yosida approx. parameter (for prox. comp.)

% MCMC algorithm to run
[logPiTrace,...
    mse_from_burnIn,...
    mse_stationarity,...
    firstMoment,...
    secondMoment] = SKROCK('true_img',X,...
                          'obs_vector',Y,...
                          'operator',A,...
                          'transpose_operator',At,...
                          'operator_transpose_operator',AtA,...
                          'inverse_precision_matrix',invQ,...
                          'number_samples_burn_in',nSamples_burnIn,...
                          'number_samples_stationarity',nSamples,...
                          'hyperparam_tv',alpha,...
                          'moreau_yosida_param',MYParam,...
                          'sigma',sigma,...
                          'lipschitz_constant_f',lipschitz_f,...
                          'n_stages',nStagesROCK,...
                          'perc_dt',percDt,...
                          'rho_2',rho2);

%-------------------------------------------------------------------------%
% Plotting results                                                        
plot_results(At(Y),...
             X,...
             nStagesROCK,...
             firstMoment,...
             logPiTrace,...
             mse_stationarity,...
             secondMoment);     
%-------------------------------------------------------------------------%