%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                       % 
%    THE SPLIT GIBBS SAMPLER REVISITED: IMPROVEMENTS TO ITS ALGORITHMIC %
%    STRUCTURE AND AUGMENTED TARGET DISTRIBUTION                        %
%                                                                       %
%    To reproduce some of the numerical experiments illustrated in the  %
%    corresponding paper.                                               %
%                                                                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% to clear workspace
clear all;
close all;

%%% number of core processors
maxNumCompThreads(1);

% import folders
addpath sampling_algorithms;
addpath numerical_experiments;
addpath functions;
addpath images;

%%% initialize the random number generator to make the results repeatable
rng('default');
% %%% initialize the generator using a seed
rng(10);

% loading functions/variables/operators from numerical experiment
[X,Y,sigma,A,H_FFT,At,AtA,invQ] = cameraman_deconvolution();

% estimating hyperparameters using
% SAPG algorithm (see Algorithm 3.1 from paper)
[alpha, rho2] = SAPG_deb_TV('true_img',X,...
                            'obs_vector',Y,...
                            'blurring_fourier_operator',H_FFT,...
                            'transpose_operator',At,...
                            'number_samples_burn_in',1e3,...
                            'max_number_samples',1e5,...
                            'sigma',sigma,...
                            'tol_tv_param',1e-4,...
                            'tol_rho2_param',1e-4)

% MCMC sampler parameters
nSamples_burnIn = 5e2;
nSamples = 1e3;
lipschitz_f = 1 / sigma^2;
nStagesROCK = 15;
percDt = 0.95;
MYParam = sigma^2;

% MCMC algorithm to run
[logPiTrace,...
    mse_from_burnIn,...
    mse_stationarity,...
    firstMoment,...
    secondMoment] = SKROCK('true_img',X,...
                          'obs_vector',Y,...
                          'operator',A,...
                          'blurring_fourier_operator',H_FFT,...
                          'transpose_operator',At,...
                          'operator_transpose_operator',AtA,...
                          'number_samples_burn_in',nSamples_burnIn,...
                          'number_samples_stationarity',nSamples,...
                          'hyperparam_tv',alpha,...
                          'moreau_yosida_param',MYParam,...
                          'sigma',sigma,...
                          'lipschitz_constant_f',lipschitz_f,...
                          'n_stages',nStagesROCK,...
                          'perc_dt',percDt,...
                          'rho_2',rho2);

%-------------------------------------------------------------------------%
% Plotting results                                                        
plot_results(Y,...
             X,...
             nStagesROCK,...
             firstMoment,...
             logPiTrace,...
             mse_stationarity,...
             secondMoment);     
%-------------------------------------------------------------------------%